# Generated by Django 2.1.2 on 2018-10-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181012_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='body',
            new_name='text',
        ),
    ]
