# Generated by Django 2.1.2 on 2018-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181012_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_level',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
