# Generated by Django 2.1.2 on 2018-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questions_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='added_by',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
