# Generated by Django 2.1.2 on 2018-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181012_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('question_level', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
