# Generated by Django 2.1.2 on 2018-10-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20181013_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.CharField(choices=[('Low', 'Junior'), ('Medium', 'Profesional'), ('High', 'Senior')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('ISTQB', 'ISTQB'), ('Object Orientated Prgramming', 'OOP'), ('Personal questions', 'Personal')], max_length=200),
        ),
    ]
