# Generated by Django 2.1.2 on 2018-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20181013_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
