# Generated by Django 2.1.2 on 2018-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181013_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('ISTQB', 'ISTQB'), ('OOP', 'Object Orientated Programming'), ('Personal questions', 'Personal'), ('CAN', 'CAN')], max_length=200),
        ),
    ]
