# Generated by Django 2.1.2 on 2018-10-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20181016_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Low', 'Junior'), ('Medium', 'Profesional'), ('High', 'Senior'), ('N/A', 'Not applicable')], max_length=200),
        ),
    ]
