# Generated by Django 2.1.2 on 2018-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181016_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='dificulty_level',
            field=models.CharField(choices=[('Junior', 'Low:'), ('Profesional', 'Medium'), ('Senior', 'High'), ('N/A', 'Not applicable')], default=('N/A', 'Not applicable'), max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('ISTQB', 'ISTQB'), ('OOP', 'Object Orientated Programming'), ('Personal', 'Personal question'), ('CAN', 'CAN'), ('Logic', 'Logical question')], max_length=200),
        ),
    ]
