# Generated by Django 2.1.2 on 2018-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20181016_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dificulty_level',
            field=models.CharField(choices=[('Junior', 'Low'), ('Profesional', 'Medium'), ('Senior', 'High'), ('N/A', 'Not applicable')], default='N/A', max_length=200),
        ),
    ]
