# Generated by Django 2.1.2 on 2018-10-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_candidates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Candidate',
        ),
    ]
