# Generated by Django 2.1.2 on 2018-10-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20181027_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='client',
            field=models.CharField(max_length=200, verbose_name=[('ADP', 'ADP'), ('FICOSA', 'FICOSA'), ('HP', 'HP'), ('Kaba', 'Kaba'), ('Omrom', 'Omrom'), ('Roche', 'Roche'), ('Vueling', 'Vueling')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='recruiter',
            field=models.CharField(choices=[('Guillermo', 'Guillermo Lopez'), ('Vernonica', 'Verónica Mendes'), ('Alberto', 'Alberto Arjona'), ('Luisa', 'Luisa Cabrera'), ('Oscar', 'Oscar Penon'), ('Monika', 'Monika Szymanska')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(max_length=200, verbose_name=[('In process', 'In process'), ('Pass all process', 'Pass all process'), ('Rejeced after techncal interview', 'Rejeced after techncal interview'), ('Descarded REC', 'Descarded REC'), ('Reject pre-offer', 'Reject pre-offer'), ('Reject Offer', 'Reject Offer')]),
        ),
    ]
