# Generated by Django 2.1.2 on 2018-10-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20181027_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='client',
            field=models.CharField(choices=[('ADP', 'ADP'), ('FICOSA', 'FICOSA'), ('HP', 'HP'), ('Kaba', 'Kaba'), ('Omrom', 'Omrom'), ('Roche', 'Roche'), ('Vueling', 'Vueling')], max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('In process', 'In process'), ('Stand By for other opportunities', 'Stand By for other opportunities'), ('Pass all process', 'Pass all process'), ('Rejeced after techncal interview', 'Rejeced after techncal interview'), ('Rejeced by BUL', 'Rejeced by BUL'), ('Rejeced by client', 'Rejeced by client'), ('Descarded REC', 'Descarded REC'), ('Reject pre-offer', 'Reject pre-offer'), ('Reject Offer', 'Reject Offer')], max_length=200),
        ),
    ]
